# Generated by Django 4.1.2 on 2022-10-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='feature',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='features',
            name='icone',
            field=models.CharField(choices=[('lni-laptop-phone', 'Phone e laptop'), ('lni-stats-up', 'Gráfico'), ('lni-leaf', 'folha'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete')], max_length=19, verbose_name='Icone'),
        ),
    ]
