# Generated by Django 4.1.2 on 2022-10-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_features_feature_alter_features_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='posicao',
            field=models.CharField(choices=[('E', 'à esquerdda'), ('D', 'à direita')], default=1, max_length=1, verbose_name='Posição na página:'),
            preserve_default=False,
        ),
    ]
